<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Grupo DataPrecio">

<title>Análisis de la evolución de precios de la canasta básica: Un enfoque comparativo entre supermercados.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Informe_files/libs/clipboard/clipboard.min.js"></script>
<script src="Informe_files/libs/quarto-html/quarto.js"></script>
<script src="Informe_files/libs/quarto-html/popper.min.js"></script>
<script src="Informe_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Informe_files/libs/quarto-html/anchor.min.js"></script>
<link href="Informe_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Informe_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Informe_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Informe_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Informe_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análisis de la evolución de precios de la canasta básica: Un enfoque comparativo entre supermercados.</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Grupo DataPrecio </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>Crespo, Leonardo - 26.260.451</p>
<p>Gómez, Alexandra - 29.765.256</p>
<p>Goncalves, Ignacio - 27.600.050</p>
<p>Lara, Roselyn - 30.138.648</p>
<p>Ruiz, Halena - 29.756.414</p>
</blockquote>
<section id="identificación-del-problema" class="level2" style="color: #F0DAA4">
<h2 style="color: #F0DAA4" class="anchored" data-anchor-id="identificación-del-problema">Identificación del Problema</h2>
<p>Las variaciones de precios, en situaciones normales, son o bien ajustes naturales o presiones inflacionarias moderadas que permiten a los agentes económicos adaptarse en cierta medida. Sin embargo, en las últimas décadas, la economía venezolana ha sufrido constantemente variaciones de precios que se han transformado en fuentes de incertidumbre extrema y de empobrecimiento generalizado. El nivel de precios no solo aumenta constantemente, sino que las magnitudes de estos incrementos y la frecuencia con la que ocurren son impredecibles, lo cual impide a los agentes económicos formar expectativas sólidas y los hace enfrentarse a un constante y pronunciado declive de su poder adquisitivo.</p>
<p>Esta variación de precios se ha visto potenciada por un conjunto de factores interrelacionados como el período de hiperinflación sostenida, que destruyó la confianza en la moneda, la implementación errada de controles de precios, que generaron escasez generalizada y el crecimiento de mercados informales. Otra de las razones fue la contracción de la producción nacional y el control excesivo del sistema cambiario, lo que contribuye a la distorsión de los mecanismos de fijación de precios y disponibilidad de productos.</p>
<p>Si bien en la actualidad ya no estamos en un en un escenario de hiperinflación, la variación de los precios sigue siendo volátil, presentando aumentos significativo en diversas áreas, particularmente en <strong>alimentos</strong>, lo que impacta en el acceso de la canasta básica de alimentos para cubrir los niveles de subsistencia.</p>
<p>Ante este escenario surgen interrogantes: <u><em>¿Están subiendo los precios? ¿En qué períodos hay mayores aumentos? ¿Las instituciones de venta de alimentos formales, entendidos como supermercados, automercados o hipermercados, cuentan con precios accesibles y competitivos para que los hogares puedan adquirir los productos de la canasta básica?</em></u></p>
<hr>
</section>
<section id="elección-de-los-datos-y-la-canasta-básica" class="level2" style="color: #F0DAA4">
<h2 style="color: #F0DAA4" class="anchored" data-anchor-id="elección-de-los-datos-y-la-canasta-básica">Elección de los Datos y la Canasta Básica</h2>
<p>Este estudio aspira a generar un aporte empírico significativo para la comprensión de la evolución de precios. La investigación se justifica por la imperante necesidad de comprender la dinámica evolutiva de los precios en Venezuela, un fenómeno caracterizado por una marcada volatilidad directamente atribuible a la compleja coyuntura política y sus repercusiones macroeconómicas. Ante este escenario de inestabilidad, la disponibilidad y el análisis sistemático de datos sobre precios al consumidor se tornan cruciales para evaluar su impacto en el poder adquisitivo y el bienestar social de los hogares.</p>
<p>La selección de <strong><code>DataPrecio</code></strong>, una plataforma digital que consolida y recopila precios de productos en diversos establecimientos minoristas, se fundamenta en su capacidad para ofrecer una granularidad y accesibilidad de datos indispensables para el análisis microeconómico del consumo. Para garantizar la representatividad y la robustez del estudio <em>longitudinal</em>, se procedió a la elección de <strong>tres supermercados</strong> que exhiben una trayectoria operativa consolidada y una presencia significativa en el mercado: <code>Autosmercados Plazas</code>, <code>Central Madeirense</code> y <code>Gama Supermercados</code>.</p>
<p>La construcción de una <strong>canasta básica</strong> se realizó bajo criterios de consumo racional orientados a los hogares de <em>cinco</em> miembros de esta investigación, priorizando la identificación de <em>productos comunes y comparables entre los supermercados</em> seleccionados. A partir de esta investigación, surge como interrogante principal determinar <u><strong>cuál de los supermercados analizados ofrece la opción más ventajosa para la adquisición de la cesta básica representativa</strong></u>.</p>
<hr>
</section>
<section id="obtención-y-filtrado-de-los-datos" class="level2" style="color: #F0DAA4">
<h2 style="color: #F0DAA4" class="anchored" data-anchor-id="obtención-y-filtrado-de-los-datos">Obtención y Filtrado de los Datos</h2>
<section id="obtención" class="level3" style="color: #F0DAA4">
<h3 style="color: #F0DAA4" class="anchored" data-anchor-id="obtención">Obtención</h3>
<p>El proceso de extracción de datos se realizó mediante un <strong>scraper</strong> diseñado con la ayuda del profesor José Avendaño, para extraer los datos de los distintos productos alojados en <code>Dataprecio.com</code>. Para lograrlo, se utilizó la librería <code>httr2</code> para enviar solicitudes <strong>HTTP</strong> al <strong>API</strong> y recibir las respuestas de la página web, que están en formato <strong>JSON</strong>. Para extraer todos los datos contenidos en los JSONs, se utilizó la librería <code>jsonlite</code>, permitiendo el acceso a la información de productos y tiendas.</p>
<p>Dentro de estos archivos también había más información relevante, por lo que se tuvo que desanidar, con la función <code>unnest</code>, la categoría en cuestión. Para poder descargar todos los datos automáticamente, y no por cada pagina de Dataprecios, se implementó un <strong>loop</strong>, del tipo <strong><em>“for loops”</em></strong>. Para unir toda la información descargada en un solo dataframe, se usó <code>bind_rows()</code>.</p>
</section>
<section id="filtrado" class="level3" style="color: #F0DAA4">
<h3 style="color: #F0DAA4" class="anchored" data-anchor-id="filtrado">Filtrado</h3>
<p>El proceso de filtrado de los productos seleccionados en la canasta se realizó a través de la selección de los <code>productID</code>, posterior a esto, se necesitó hacer un código para filtrar los supermercados <em>que cumplieran con la condición de que <u>se repitieran los mismos productos</u></em>, para que <em>al totalizar la canasta <u>no hubieran discrepancias en el cálculo</u> por productos faltantes</em>. De este filtrado se escogieron tres supermercados que poseían los mismos productos (Plaza’s, Gama y el Central Madeirense).</p>
<p>Para poder hacer el análisis y el gráfico de la evolución de precios, se realizó otro dataframe, llamado <code>df_ipc</code>; en donde se unieron los distintos dataframes de días anteriores, con la funcion <code>bind_rows</code>, y se filtraron los productos de la canasta y los supermercados Plaza’s, Gama y el Central Madeirense. Luego, se construyeron dataframes por cada supermercado, y se totalizó el IPC de cada uno, para construir el dataframe con el historico, llamado <code>ipc_datapanel</code>.&nbsp;</p>
</section>
<section id="limitaciones-temporales" class="level3" style="color: #F0DAA4">
<h3 style="color: #F0DAA4" class="anchored" data-anchor-id="limitaciones-temporales">Limitaciones Temporales</h3>
<p>Seria óptimo seguir desarrollando el proyecto para realizar los siguientes puntos:</p>
<ul>
<li><p>Automatización de la descarga diaria de datos para la construcción de una base.</p></li>
<li><p>Automatización del data frame <code>df_ipc</code> que alimenta al dashboard, para que vaya agregando por sí solo los datos nuevos, y dashboard se actualice diariamente.</p></li>
<li><p>Dado a que hay múltiples productos sustitutos, no coincidentes en fabricantes, en las distintas tiendas que abarca dataprecios, posiblemente se puedan igualar <code>productIDs</code> de productos sustitutos de distinta marca, para que el análisis no sólo este en tres supermercados, sino que abarque un número mayor de estos.</p></li>
</ul>
<hr>
</section>
</section>
<section id="análisis-exploratorio-de-los-datos" class="level2" style="color: #F0DAA4">
<h2 style="color: #F0DAA4" class="anchored" data-anchor-id="análisis-exploratorio-de-los-datos">Análisis Exploratorio de los Datos</h2>
<section id="resúmenes-estadísticos" class="level3" style="color: #F0DAA4">
<h3 style="color: #F0DAA4" class="anchored" data-anchor-id="resúmenes-estadísticos">Resúmenes Estadísticos</h3>
<p>Se utilizó la función <code>summary</code>.</p>
<section id="precios-de-dataprecio" class="level4" style="color: orchid">
<h4 style="color: orchid" class="anchored" data-anchor-id="precios-de-dataprecio"><strong>Precios de DataPrecio:</strong></h4>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Min.</td>
<td>1st Qu.</td>
<td>Median</td>
<td>Mean</td>
<td>3rd Qu.</td>
<td>Max.</td>
</tr>
<tr class="even">
<td>0.390</td>
<td>1.730</td>
<td>2.900</td>
<td>4.929</td>
<td>5.750</td>
<td>61.270</td>
</tr>
</tbody>
</table>
<p>La tabla anterior sintetiza la distribución de precios en el conjunto de datos “DataPrecios” mediante el uso de medidas estadísticas clave.</p>
<p>El <strong>valor mínimo</strong>, de $0.39, indica que el precio más bajo registrado en el conjunto de datos es de $0.39, confirmando la existencia de al menos un producto con este costo.</p>
<p>Al analizar los cuartiles, observamos que el <strong>primer cuartil (Q1)</strong> se sitúa en $1.73. Este valor significa que el 25% de los productos seleccionados en “DataPrecios” tienen un precio igual o inferior a $1.73. Por otro lado, el <strong>tercer cuartil (Q3)</strong>, con un valor de $5.75, revela que el 75% de los productos tienen un precio igual o inferior a $5.75.</p>
<p>La <strong>mediana</strong>, que es de $2.90, divide el conjunto de datos en dos mitades: el 50% de los productos tienen un precio igual o inferior a $2.90, mientras que el otro 50% posee un precio superior a este valor.</p>
<p>Finalmente, la <strong>media aritmética</strong> de los precios es de $4.92, representando el precio promedio de todos los productos en el conjunto de datos. Es notable que la media sea significativamente más alta que la mediana, lo que sugiere la presencia de algunos artículos con precios considerablemente más elevados, los cuales, al ser incluidos en el cálculo, elevan el promedio general.</p>
<hr>
</section>
<section id="precios-de-la-canasta-básica-en-los-tres-supermercados" class="level4" style="color: lightblue">
<h4 style="color: lightblue" class="anchored" data-anchor-id="precios-de-la-canasta-básica-en-los-tres-supermercados"><strong>Precios de la Canasta Básica en los Tres Supermercados:</strong></h4>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Min.</td>
<td>1st Qu.</td>
<td>Median</td>
<td>Mean</td>
<td>3rd Qu.</td>
<td>Max.</td>
</tr>
<tr class="even">
<td>0.95</td>
<td>1.69</td>
<td>2.70</td>
<td>4.28</td>
<td>5.39</td>
<td>16.30</td>
</tr>
</tbody>
</table>
<p>El <strong>valor mínimo</strong>, de $0.95, indica que el precio más bajo registrado en este conjunto de datos es de $0.95.</p>
<p>El <strong>primer cuartil (Q1)</strong>, que se sitúa en $1.69, revela que el 25% de los precios son iguales o inferiores a $1.69. Esto sugiere que una parte considerable de los productos se encuentra en un rango de costo muy bajo.</p>
<p>La <strong>mediana</strong>, con un valor de $2.70, es el punto central de la distribución: el 50% de los precios son iguales o inferiores a $2.70, y el otro 50% son superiores a este valor.</p>
<p>El <strong>tercer cuartil (Q3)</strong> es de $5.39, lo que significa que el 75% de los precios son iguales o inferiores a $5.39. Este valor muestra que incluso tres cuartas partes de los productos se encuentran en un rango de precio moderado.</p>
<p>Finalmente, el <strong>valor máximo</strong> es de $16.30, indicando el precio más alto en el conjunto de datos. La <strong>media aritmética</strong> de los precios es de $4.28.</p>
<p>Es notable que la media ($4.28) es más alta que la mediana ($2.70). Esta diferencia significativa es un indicador claro de una <strong>distribución asimétrica con un sesgo positivo o hacia la derecha</strong>. Ello implica que, aunque la mayoría de los precios son bajos (como lo sugieren el primer cuartil y la mediana), existen algunos productos con precios considerablemente más elevados que “jalan” el promedio hacia arriba.</p>
<hr>
</section>
<section id="precios-de-plazas" class="level4" style="color: lightgreen">
<h4 style="color: lightgreen" class="anchored" data-anchor-id="precios-de-plazas"><strong>Precios de Plazas:</strong></h4>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Min.</td>
<td>1st Qu.</td>
<td>Median</td>
<td>Mean</td>
<td>3rd Qu.</td>
<td>Max.</td>
</tr>
<tr class="even">
<td>0.95</td>
<td>1.79</td>
<td>2.71</td>
<td>4.40</td>
<td>5.49</td>
<td>15.99</td>
</tr>
</tbody>
</table>
<p>El <strong>valor mínimo</strong>, de $0.95, indica que el valor más bajo registrado en la distribución es de $0.95. Por otro lado, el <strong>valor máximo</strong>, de $15.99, representa el valor más alto encontrado en el conjunto de datos, delineando así el rango completo de la distribución.</p>
<p>Al examinar los cuartiles, observamos que el <strong>primer cuartil (Q1)</strong> se sitúa en $1.79. Este valor nos informa que el 25% de los datos tienen un valor igual o inferior a $1.79. El <strong>tercer cuartil (Q3)</strong>, con un valor de $5.49, revela que el 75% de los datos se encuentran en o por debajo de este valor.</p>
<p>La <strong>mediana</strong>, que es de $2.71, es una medida central que divide el conjunto de datos en dos mitades: el 50% de los datos tienen un valor igual o inferior a $2.71, y el otro 50% tiene un valor superior a éste.</p>
<p>Finalmente, la <strong>media aritmética</strong> de los datos es de $4.40, representando el valor promedio de todas las observaciones. Es importante destacar que la media es notablemente más alta que la mediana ($4.40 y $2.71). Esta discrepancia sugiere una <strong>asimetría positiva (o sesgo a la derecha)</strong> en la distribución. Dicha asimetría implica la existencia de valores atípicos o una cola de datos con valores más altos que, aunque menos frecuentes, influyen en el promedio, elevándolo por encima del punto central que representa la mediana.</p>
<hr>
</section>
<section id="precios-del-central-madeirense" class="level4" style="color: pink">
<h4 style="color: pink" class="anchored" data-anchor-id="precios-del-central-madeirense"><strong>Precios del Central Madeirense:</strong></h4>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Min.</td>
<td>1st Qu.</td>
<td>Median</td>
<td>Mean</td>
<td>3rd Qu.</td>
<td>Max.</td>
</tr>
<tr class="even">
<td>0.960</td>
<td>1.680</td>
<td>2.700</td>
<td>4.157</td>
<td>5.010</td>
<td>16.300</td>
</tr>
</tbody>
</table>
<p>El <strong>valor mínimo</strong>, de $0.960, indica que el precio más bajo registrado en esta distribución es cercano a un dólar.</p>
<p>El <strong>primer cuartil (Q1)</strong>, que se sitúa en $1.680, revela que el 25% de los productos tienen un precio igual o inferior a $1.68. Esto subraya que una proporción considerable de los artículos se encuentra en un rango de costos muy bajo.</p>
<p>La <strong>mediana</strong> es de $2.700, lo que significa que el 50% de los productos tienen un precio de $2.70 o menos, y la otra mitad supera este valor. Este punto medio de la distribución es relativamente bajo.</p>
<p>El <strong>tercer cuartil (Q3)</strong> tiene un valor de $5.010, indicando que el 75% de los productos se venden a un precio igual o inferior a $5.01.</p>
<p>Finalmente, el <strong>valor máximo</strong> registrado es de $16.300, lo que representa el precio más alto dentro del conjunto de datos.</p>
<p>La <strong>media aritmética</strong> de los precios es de $4.157, constituyendo el precio promedio. Es relevante notar que la media ($4.157) es significativamente más alta que la mediana ($2.700). Esta disparidad es un fuerte indicativo de una <strong>distribución asimétrica con una cola hacia la derecha</strong>; es decir, existen algunos productos con precios considerablemente más elevados que elevan el promedio, a pesar de que la mayoría de los productos se concentran en el rango de precios más bajo.</p>
<hr>
</section>
<section id="precios-del-gama" class="level4" style="color: #FAEB92">
<h4 style="color: #FAEB92" class="anchored" data-anchor-id="precios-del-gama"><strong>Precios del Gama:</strong></h4>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Min.</td>
<td>1st Qu.</td>
<td>Median</td>
<td>Mean</td>
<td>3rd Qu.</td>
<td>Max.</td>
</tr>
<tr class="even">
<td>0.950</td>
<td>1.690</td>
<td>2.640</td>
<td>4.284</td>
<td>4.990</td>
<td>13.500</td>
</tr>
</tbody>
</table>
<p>El <strong>valor mínimo</strong>, de $0.95, indica que este es el precio más bajo registrado en el conjunto de datos.</p>
<p>Al examinar los cuartiles, observamos que el <strong>primer cuartil (Q1)</strong> se sitúa en $1.69. Este dato nos dice que el 25% de los precios en la distribución son iguales o inferiores a $1.69. Por otro lado, el <strong>tercer cuartil (Q3)</strong>, con un valor de $4.99, revela que el 75% de los precios son iguales o inferiores a $4.99.</p>
<p>La <strong>mediana</strong>, que es de $2.64, divide el conjunto de datos en dos partes iguales: el 50% de los precios son iguales o inferiores a $2.64, mientras que el 50% restante supera este valor.</p>
<p>Finalmente, la <strong>media aritmética</strong> de los precios es de $4.284. Es notable que la media sea significativamente más alta que la mediana ($4.284 y $2.64). Esta disparidad es un fuerte indicador de una distribución asimétrica positiva (sesgada a la derecha), lo que implica la existencia de precios más altos que, aunque menos frecuentes, influyen en el promedio, elevándolo por encima del punto medio de los datos. El valor máximo, de $13.50, confirma la presencia de estos precios más elevados que contribuyen a esta asimetría.</p>
<hr>
</section>
</section>
<section id="gráficos-exploratorios" class="level3" style="color: #F0DAA4">
<h3 style="color: #F0DAA4" class="anchored" data-anchor-id="gráficos-exploratorios">Gráficos Exploratorios</h3>
<section id="histogramas" class="level4" style="color: #F0DAA4">
<h4 style="color: #F0DAA4" class="anchored" data-anchor-id="histogramas">✔ Histogramas</h4>
</section>
<section id="histograma-de-los-precios-en-dataprecios" class="level4" style="color: orchid">
<h4 style="color: orchid" class="anchored" data-anchor-id="histograma-de-los-precios-en-dataprecios">Histograma de los precios en DataPrecios</h4>
<p><img src="images/clipboard-15861576.png" class="img-fluid"></p>
<p>Este gráfico representa la distribución de la frecuencia de precios de los productos, expresados en dólares. El <strong>eje horizontal (X)</strong>, etiquetado como “Intervalos de Precios”, muestra rangos de precios que van desde 0 hasta 60 dólares, con intervalos de 5 dólares. Por su parte, el <strong>eje vertical (Y)</strong>, denominado “Frecuencia de Productos”, indica el número de productos que se encuentran dentro de cada intervalo, abarcando una escala que supera las 2000 unidades.</p>
<p>La característica más destacada del histograma es la barra correspondiente al <strong>primer intervalo (0-5 dólares)</strong>. Su altura excepcional, superando los 2000 productos, revela que la vasta mayoría de los productos se concentran en este rango de precios. A medida que los precios aumentan, la frecuencia de productos disminuye de forma drástica, evidenciando una clara tendencia.</p>
<p>El histograma presenta una <strong>cola larga hacia la derecha</strong>, lo que sugiere una distribución asimétrica. Esto indica la existencia de muy pocos productos con precios más elevados, distribuidos en un rango más amplio. Los intervalos entre 15 y 45 dólares muestran frecuencias extremadamente bajas, lo que confirma la escasez de productos en esos rangos. Se aprecian pequeñas barras residuales alrededor de los 45-50 y 50-55 dólares, lo que, aunque mínima, señala la presencia de algunos productos con precios considerablemente más altos.</p>
<ul>
<li><p>La <strong>mayoría de los productos son de bajo costo</strong>.</p></li>
<li><p>Existen <strong>pocos productos de alto costo</strong>.</p></li>
<li><p>La distribución de precios es <strong>asimétrica</strong>.</p></li>
</ul>
<hr>
</section>
<section id="histograma-de-la-canasta-básica-de-automercados-plaza" class="level4" style="color: lightgreen">
<h4 style="color: lightgreen" class="anchored" data-anchor-id="histograma-de-la-canasta-básica-de-automercados-plaza">Histograma de la Canasta Básica de Automercados Plaza</h4>
<p><img src="images/clipboard-3646499738.png" class="img-fluid"></p>
<p>Este histograma ilustra la distribución de la frecuencia de los precios de los productos que componen la canasta básica en el supermercado Plaza’s, expresados en dólares. El <strong>eje horizontal (X)</strong>, denominado “Intervalos de precios”, muestra los rangos de precios de los productos, abarcando desde 0 hasta aproximadamente 16 dólares, con intervalos que parecen ser de 2 a 3 dólares. El <strong>eje vertical (Y)</strong>, titulado “Frecuencia de productos”, indica la cantidad de productos que se agrupan dentro de cada intervalo de precios, con una escala que asciende hasta las 10 unidades.</p>
<p>La característica más sobresaliente de este histograma es la <strong>dominante concentración de productos en el primer intervalo de precios</strong> (aproximadamente 0-2 o 0-3 dólares). Esta barra alcanza la frecuencia máxima de 10 unidades de productos, lo que indica que una proporción muy significativa de los artículos de la canasta básica en Plaza’s se encuentran en el rango de precios más bajo.</p>
<p>A partir de este pico inicial, la frecuencia de los productos disminuye progresivamente en los siguientes intervalos (aproximadamente 3-6 dólares, con 6 y 7 unidades, y 6-9 dólares con 1 unidad). Sin embargo, se observa un <strong>patrón interesante y diferenciador</strong> en los rangos de precios más altos. Existe un <strong>repunte notable en el intervalo aproximado de 12-15 dólares</strong>, donde la frecuencia asciende a 3 unidades, lo que sugiere la presencia de una cantidad considerable de productos en ese rango comparado con los inmediatamente anteriores. Además, hay una barra de 1 unidad en el siguiente intervalo (aproximadamente 15-18 dólares), indicando que, aunque escasos, existen algunos productos con precios más elevados.</p>
<ul>
<li><p>La <strong>abrumadora mayoría de los productos de la canasta básica en Plaza’s son de muy bajo costo</strong>.</p></li>
<li><p>La distribución de precios es <strong>claramente asimétrica, sesgada hacia los valores más bajos</strong>.</p></li>
<li><p>A pesar de la fuerte concentración en precios bajos, hay una <strong>presencia notable de productos en un rango de precios moderadamente más altos</strong> (alrededor de 12-15 dólares), lo que le da una forma distintiva a la cola de la distribución.</p></li>
</ul>
<hr>
</section>
<section id="histograma-de-la-canasta-básica-de-central-madeirense" class="level4" style="color: pink">
<h4 style="color: pink" class="anchored" data-anchor-id="histograma-de-la-canasta-básica-de-central-madeirense">Histograma de la Canasta Básica de Central Madeirense</h4>
<p><img src="images/clipboard-3936848625.png" class="img-fluid"></p>
<p>Este histograma ilustra la distribución de la frecuencia de los precios de los productos que componen la canasta básica en el supermercado Central Madeirense, expresados en dólares. El <strong>eje horizontal (X)</strong>, denominado “Intervalos de Precios”, muestra los rangos de precios de los productos, abarcando desde 0 hasta aproximadamente 18-20 dólares, con intervalos que parecen ser de 2 a 3 dólares. El <strong>eje vertical (Y)</strong>, titulado “Frecuencia de productos”, indica el número de productos que caen dentro de cada intervalo de precios, con una escala que asciende hasta las 8 unidades.</p>
<p>La característica más sobresaliente de este histograma es la marcada concentración de productos en los <strong>intervalos de precios más bajos</strong>. Específicamente, el primer intervalo (aproximadamente 0-2 o 0-3 dólares) y el segundo intervalo (aproximadamente 3-6 dólares) presentan las frecuencias más altas, con la primera barra superando las 8 unidades y la segunda alcanzando las 6 unidades de productos. Esto indica que la mayoría de los productos de la canasta básica en Central Madeirense tienen un costo relativamente bajo.</p>
<p>A medida que los precios aumentan, la frecuencia de los productos disminuye notablemente. Aunque se observa una pequeña concentración en el rango de 9-12 dólares (con dos barras de 2 unidades), la distribución general muestra que hay muchos menos productos en los rangos de precios intermedios y altos. Los intervalos posteriores, como el de 12-15 dólares, muestran una frecuencia muy baja (1 unidad), y finalmente, hay una barra aislada alrededor de los 16-18 dólares (1 unidad), sugiriendo la presencia de uno o muy pocos productos con precios considerablemente más altos, aunque sumamente escasos dentro de la canasta básica.</p>
<ul>
<li><p>La <strong>mayoría de los productos de la canasta básica son de bajo costo</strong>.</p></li>
<li><p>La <strong>cantidad de productos disminuye significativamente a medida que el precio aumenta</strong>.</p></li>
<li><p>La distribución de precios es <strong>claramente asimétrica</strong>, con una fuerte inclinación hacia los valores más bajos.</p></li>
</ul>
<hr>
</section>
<section id="histograma-de-la-canasta-básica-de-gama-supermercados" class="level4" style="color: #FAEB92">
<h4 style="color: #FAEB92" class="anchored" data-anchor-id="histograma-de-la-canasta-básica-de-gama-supermercados">Histograma de la Canasta Básica de Gama Supermercados</h4>
<p><img src="images/clipboard-1423526574.png" class="img-fluid"></p>
<p>Este histograma presenta la distribución de la frecuencia de los precios de los productos que conforman la canasta básica en el supermercado Gama, expresados en dólares. El <strong>eje horizontal (X)</strong>, identificado como “Intervalos de precios”, muestra los rangos de precios de los productos, extendiéndose desde 0 hasta aproximadamente 14-15 dólares, con intervalos que parecen ser de 2 a 3 dólares. El <strong>eje vertical (Y)</strong>, denominado “Frecuencia de productos”, indica la cantidad de productos que se agrupan dentro de cada intervalo de precios, con una escala que alcanza las 9 unidades.</p>
<p>Al igual que en los análisis anteriores, la característica más prominente de este histograma es la alta concentración de productos en los rangos de precios más bajos. Específicamente, el primer intervalo (aproximadamente 0-2 o 0-3 dólares) y el segundo intervalo (aproximadamente 3-6 dólares) exhiben las frecuencias más elevadas, con el primer rango mostrando 8 unidades y el segundo alcanzando 9 unidades de productos. Esto subraya que la mayoría de los artículos de la canasta básica en Gama tienen un costo contenido.</p>
<p>A medida que los precios aumentan, la frecuencia de los productos experimenta una disminución general, aunque con algunas fluctuaciones. Se observa una caída notable en los intervalos intermedios (aproximadamente 6-9 dólares, con 2 unidades, y 9-12 dólares, con 1 y 2 unidades respectivamente). Sin embargo, se presenta un <strong>ligero repunte en el rango de precios más altos</strong> representados en el gráfico (aproximadamente 12-15 dólares), donde la frecuencia asciende nuevamente a 3 unidades. Esto sugiere que, si bien la mayoría de los productos son de bajo costo, hay un grupo de productos de precios moderadamente más altos que no son tan escasos como en distribuciones con colas más largas y continuas.</p>
<ul>
<li><p>La <strong>mayoría de los productos de la canasta básica son de bajo costo</strong>.</p></li>
<li><p>La distribución muestra una <strong>asimetría hacia la izquierda</strong>, con la mayor concentración en los precios más bajos.</p></li>
<li><p>Existe una <strong>presencia moderada de productos en rangos de precios ligeramente más elevados</strong> (cerca de los 12-15 dólares), diferenciándose de una cola extremadamente larga y delgada.</p></li>
</ul>
<hr>
</section>
<section id="gráficos-de-densidad" class="level4">
<h4 class="anchored" data-anchor-id="gráficos-de-densidad">✔ Gráficos de Densidad</h4>
</section>
<section id="densidad-de-los-precios-en-dataprecios" class="level4" style="color: orchid">
<h4 style="color: orchid" class="anchored" data-anchor-id="densidad-de-los-precios-en-dataprecios">Densidad de los precios en DataPrecios</h4>
<p><img src="images/clipboard-1460571218.png" class="img-fluid"></p>
<p>Este gráfico de densidad representa la distribución de la probabilidad de los precios de los productos en dólares, a partir del conjunto de datos “DataPrecio”. El <strong>eje horizontal (X)</strong> muestra los precios en dólares, abarcando un rango que va desde 0 hasta aproximadamente 65 dólares. El <strong>eje vertical (Y)</strong>, denominado “Density” (Densidad), indica la probabilidad relativa de observar un precio en un punto determinado. En la parte inferior se informa que el número total de observaciones es N = 3193 y el ancho de banda utilizado para la estimación es Bandwidth = 0.5377.</p>
<p>La característica más sobresaliente de esta distribución es su <strong>marcada asimetría y la fuerte concentración de precios en el rango más bajo</strong>. Se observa un <strong>pico extremadamente alto y estrecho muy cerca de 0 dólares</strong>, lo que indica que la inmensa mayoría de los productos tienen precios muy bajos, probablemente entre 0 y 5 dólares. Este pico dominante revela que la densidad de productos es máxima en este rango inicial.</p>
<p>A medida que los precios aumentan, la densidad de probabilidad disminuye drásticamente, formando una <strong>cola larga y extendida hacia la derecha</strong>. Esto significa que hay una cantidad significativamente menor de productos a medida que los precios se elevan. Aunque la densidad es muy baja, la cola se extiende hasta aproximadamente los 60 dólares, lo que sugiere que existen algunos productos con precios considerablemente más altos, pero son muy escasos en comparación con la gran masa de productos de bajo costo. Se observan algunas pequeñas ondulaciones en esta cola (por ejemplo, alrededor de los 15-20 dólares, 40-45 dólares), lo que podría indicar la presencia de grupos muy reducidos de productos en esos rangos específicos, aunque con una densidad muy baja.</p>
<ul>
<li><p>La <strong>distribución de precios está fuertemente sesgada hacia la izquierda</strong>, con la gran mayoría de los productos concentrados en el rango de precios más bajo.</p></li>
<li><p>La <strong>diversidad de productos disminuye drásticamente a medida que los precios aumentan</strong>, evidenciando que hay muy pocos artículos costosos.</p></li>
<li><p>La <strong>presencia de una “cola larga” a la derecha</strong> indica que, aunque la mayoría es de bajo costo, existen algunos productos de alto precio, pero son extremadamente raros en el conjunto de datos.</p></li>
</ul>
<hr>
</section>
<section id="densidad-de-los-precios-en-la-canasta-básica-de-automercados-plaza" class="level4" style="color: lightgreen">
<h4 style="color: lightgreen" class="anchored" data-anchor-id="densidad-de-los-precios-en-la-canasta-básica-de-automercados-plaza">Densidad de los precios en la Canasta Básica de Automercados Plaza</h4>
<p><img src="images/clipboard-1928122122.png" class="img-fluid"></p>
<p>Este gráfico de densidad representa la distribución de la probabilidad de los precios de los productos que componen la canasta básica en el supermercado Plaza’s, expresados en dólares. El <strong>eje horizontal (X)</strong> muestra los precios en dólares, abarcando un rango que va desde 0 hasta aproximadamente 20 dólares. El <strong>eje vertical (Y)</strong>, denominado “Density” (Densidad), indica la probabilidad relativa de observar un precio en un punto determinado. En la parte inferior se informa que el número total de observaciones es N = 31 y el ancho de banda utilizado para la estimación es Bandwidth = 1.347.</p>
<p>La característica más notable de esta distribución es su <strong>naturaleza bimodal</strong>, lo que sugiere la existencia de dos grupos principales de precios dentro de la canasta básica de Plaza’s.</p>
<p>Entre estos dos picos, la densidad de probabilidad disminuye significativamente (aproximadamente entre 5 y 10 dólares), indicando que hay menos productos en estos rangos de precios intermedios. Después del segundo pico, la densidad vuelve a disminuir gradualmente, extendiéndose la cola hacia los 20 dólares, lo que implica que hay muy pocos productos con precios superiores a los 15 dólares.</p>
<ul>
<li><p>La <strong>distribución de precios en Plaza’s es bimodal</strong>, con dos concentraciones principales: una mayoría de productos de muy bajo costo (alrededor de $2-3) y un grupo secundario de productos con precios más elevados (alrededor de $12-13).</p></li>
<li><p>Existe una <strong>brecha notable en la densidad de productos</strong> en los rangos de precios intermedios (aproximadamente $5-10).</p></li>
<li><p>La presencia de dos picos distintos sugiere que la canasta básica en Plaza’s no tiene una distribución de precios uniforme, sino que se agrupa en torno a estos dos niveles de costo.</p></li>
</ul>
<hr>
</section>
<section id="densidad-de-los-precios-en-la-canasta-básica-de-central-madeirense" class="level4" style="color: pink">
<h4 style="color: pink" class="anchored" data-anchor-id="densidad-de-los-precios-en-la-canasta-básica-de-central-madeirense">Densidad de los precios en la Canasta Básica de Central Madeirense</h4>
<p><img src="images/clipboard-3502864055.png" class="img-fluid"></p>
<p>Este gráfico de densidad representa la distribución de la probabilidad de los precios de los productos que componen la canasta básica en el supermercado Central Madeirense, expresados en dólares. El <strong>eje horizontal (X)</strong> muestra los precios en dólares, abarcando un rango que va desde 0 hasta aproximadamente 20 dólares. El <strong>eje vertical (Y)</strong>, denominado “Density” (Densidad), indica la probabilidad relativa de observar un precio en un punto determinado. En la parte inferior se informa que el número total de observaciones es N = 31 y el ancho de banda utilizado para la estimación es Bandwidth = 1.303.</p>
<p>La característica más prominente de esta distribución es su <strong>fuerte asimetría positiva</strong> (sesgo a la derecha) y la concentración inicial de precios. La forma general de la curva indica que, si bien la mayoría de los productos son de bajo costo, hay una proporción menor de artículos con precios más altos que se distribuyen a lo largo de un rango considerable.</p>
<ul>
<li><p>La <strong>distribución de precios en Central Madeirense es marcadamente asimétrica y sesgada hacia la derecha</strong>, con la gran mayoría de los productos siendo de bajo costo.</p></li>
<li><p>La <strong>mayor concentración de productos se encuentra entre los 2 y 3 dólares</strong>.</p></li>
<li><p>Existe una <strong>cola larga y con algunas ondulaciones</strong>, lo que sugiere la presencia de productos de mayor precio, aunque en menor cantidad, dispersos en diferentes rangos hasta los 20 dólares.</p></li>
</ul>
<hr>
</section>
<section id="densidad-de-los-precios-en-la-canasta-básica-de-gama-supermercados" class="level4" style="color: #FAEB92">
<h4 style="color: #FAEB92" class="anchored" data-anchor-id="densidad-de-los-precios-en-la-canasta-básica-de-gama-supermercados">Densidad de los precios en la Canasta Básica de Gama Supermercados</h4>
<p><img src="images/clipboard-2981633647.png" class="img-fluid"></p>
<p>Este gráfico de densidad representa la distribución de la probabilidad de los precios de los productos que componen la canasta básica en el supermercado Gama, expresados en dólares. El <strong>eje horizontal (X)</strong> muestra los precios en dólares, abarcando un rango que va desde 0 hasta aproximadamente 18 dólares. El <strong>eje vertical (Y)</strong>, denominado “Density” (Densidad), indica la probabilidad relativa de observar un precio en un punto determinado. En la parte inferior se informa que el número total de observaciones es N = 31 y el ancho de banda utilizado para la estimación es Bandwidth = 1.369.</p>
<p>La característica más prominente de esta distribución, similar a la observada en Plaza’s, es su <strong>naturaleza bimodal</strong>, lo que sugiere la existencia de dos grupos distintos de precios dentro de la canasta básica de Gama.</p>
<p>Entre estos dos picos, la densidad de probabilidad disminuye notablemente (aproximadamente entre 5 y 10 dólares), lo que indica una menor cantidad de productos en estos rangos de precios intermedios. Después del segundo pico, la densidad vuelve a caer, extendiéndose la cola hacia los 18 dólares, lo que implica que hay muy pocos productos con precios superiores a los 15 dólares.</p>
<ul>
<li><p>La <strong>distribución de precios en Gama es bimodal</strong>, con dos concentraciones principales: una mayoría de productos de bajo costo (alrededor de $2.5-$3.5) y un grupo secundario de productos con precios más elevados (alrededor de $12-$13).</p></li>
<li><p>Existe una <strong>clara brecha en la densidad de productos</strong> en los rangos de precios intermedios.</p></li>
<li><p>La presencia de dos modas distintas refleja una estructura de precios en la canasta básica de Gama donde los productos tienden a agruparse en torno a estos dos niveles de costo.</p></li>
</ul>
<hr>
</section>
<section id="densidad-de-los-precios-en-la-canasta-básica-de-los-tres-supermercados" class="level4" style="color: lightblue">
<h4 style="color: lightblue" class="anchored" data-anchor-id="densidad-de-los-precios-en-la-canasta-básica-de-los-tres-supermercados">Densidad de los precios en la Canasta Básica de los tres supermercados</h4>
<p><img src="images/clipboard-3157122061.png" class="img-fluid"></p>
<p>Este gráfico de densidad ilustra la distribución de la probabilidad de los precios promedios de los productos de la canasta básica filtrada, considerando los datos de los supermercados Gama, Plaza’s y Central Madeirense, y expresados en dólares. El <strong>eje horizontal (X)</strong> muestra los precios en dólares, abarcando un rango que va desde 0 hasta aproximadamente 20 dólares. El <strong>eje vertical (Y)</strong>, denominado “Density” (Densidad), indica la probabilidad relativa de observar un precio promedio en un punto determinado. En la parte inferior se informa que el número total de observaciones es N = 93 y el ancho de banda utilizado para la estimación es Bandwidth = 1.085.</p>
<p>La característica más sobresaliente de esta distribución combinada es su clara <strong>naturaleza bimodal</strong>, lo que indica que, al promediar los precios de los tres supermercados, los productos de la canasta básica tienden a agruparse en torno a dos niveles de costo principales.</p>
<p>Entre estos dos picos, la densidad de probabilidad disminuye considerablemente (aproximadamente entre 5 y 10 dólares), lo que significa que hay una menor cantidad de productos con precios promedios en este rango intermedio. Después del segundo pico, la densidad vuelve a descender, formando una cola que se extiende hacia los 20 dólares, lo que implica que muy pocos productos tienen un precio promedio superior a los 15 dólares en este conjunto filtrado.</p>
<ul>
<li><p>La <strong>distribución de los precios promedios de la canasta básica filtrada es bimodal</strong>, con dos concentraciones de precios claramente definidas.</p></li>
<li><p>La <strong>mayoría de los productos promediados se encuentran en el rango de precios bajos</strong> (aproximadamente $2.5-$3.5).</p></li>
<li><p>Existe un <strong>grupo secundario importante de productos con precios promedios más altos</strong> (alrededor de $12-$13), lo que denota una dualidad en la estructura de costos de la canasta básica al considerar los promedios de los tres supermercados.</p></li>
<li><p>La <strong>escasez de productos con precios promedios en el rango intermedio</strong> subraya esta división en dos segmentos de costo.</p></li>
</ul>
<hr>
</section>
<section id="cantidad-de-productos-por-categoría" class="level4">
<h4 class="anchored" data-anchor-id="cantidad-de-productos-por-categoría">✔ Cantidad de Productos por Categoría</h4>
</section>
<section id="gráfico-de-barras-de-la-canasta-básica" class="level4" style="color: pink">
<h4 style="color: pink" class="anchored" data-anchor-id="gráfico-de-barras-de-la-canasta-básica">Gráfico de barras de la Canasta Básica</h4>
<p><img src="images/clipboard-3851474166.png" class="img-fluid"></p>
<p>Este gráfico de barras presenta la cantidad de productos disponibles para diferentes subcategorías que conforman la canasta básica. El <strong>eje horizontal (X)</strong> muestra las diversas subcategorías de productos, ordenadas de mayor a menor cantidad. El <strong>eje vertical (Y)</strong>, denominado “Cantidades”, indica el número de productos por subcategoría, abarcando una escala que va desde 0 hasta casi 80 unidades.</p>
<p>La característica más evidente del gráfico es la <strong>amplia disparidad en la disponibilidad de productos entre las diferentes subcategorías</strong>. Las subcategorías ubicadas al inicio del gráfico, como “Frutas” (aproximadamente 78 unidades), “Jabones En Barra” (alrededor de 75 unidades), “Horquillas” (cerca de 70 unidades), “Cereales” (alrededor de 65 unidades) y “Jugos Azucarados” (cerca de 63 unidades), muestran una <strong>abundancia significativamente mayor</strong> de opciones. Esto sugiere que los consumidores tienen una variedad muy amplia para elegir dentro de estos segmentos.</p>
<p>A medida que avanzamos hacia la derecha en el eje de subcategorías, se observa una <strong>disminución progresiva y constante en la cantidad de productos</strong>. Subcategorías como “Desodorantes Roll-On” (alrededor de 47 unidades), “Panes Empacados” (cerca de 40 unidades), “Champu” (alrededor de 38 unidades), “Tubérculos” (aproximadamente 35 unidades) y “Leguminosas” (cerca de 33 unidades) aún presentan una cantidad considerable, pero ya no tan dominante.</p>
<p>Finalmente, las subcategorías ubicadas hacia el extremo derecho del gráfico, como “Salchichas” (aproximadamente 7 unidades), “Quesos Blancos Duros” (cerca de 5 unidades), “Jabones Para Lavar” (alrededor de 4 unidades) y, especialmente, “Cigarrillos Y Tabacos” (con apenas 2 unidades), exhiben una <strong>disponibilidad muy limitada de productos</strong>. Esto indica una menor variedad para los consumidores que buscan artículos dentro de estos segmentos.</p>
<ul>
<li><p>Existe una <strong>clara concentración de la oferta en ciertas subcategorías de productos</strong>, principalmente “Frutas”, “Jabones En Barra” y “Horquillas”.</p></li>
<li><p>La <strong>variedad de productos disminuye gradualmente</strong> a medida que se avanza por las categorías menos representadas.</p></li>
<li><p>Algunas subcategorías, como “Cigarrillos Y Tabacos” y “Jabones Para Lavar”, muestran una <strong>cantidad de productos extremadamente baja</strong>, lo que podría limitar las opciones del consumidor.</p></li>
</ul>
<div style="color: pink">
<p><strong><em>Cabe destacar que esta fue la Canasta Básica inicialmente seleccionada, pero por la condición de filtrado mencionado en el apartado de “Obtención y Filtrado”, esta fue posteriormente recortada a la canasta visualizada en el siguiente gráfico.</em></strong></p>
</div>
<hr>
</section>
<section id="gráfico-de-barras-de-la-canasta-básica-filtrado" class="level4" style="color: orchid">
<h4 style="color: orchid" class="anchored" data-anchor-id="gráfico-de-barras-de-la-canasta-básica-filtrado">Gráfico de barras de la Canasta Básica Filtrado</h4>
<p><img src="images/clipboard-3156558686.png" class="img-fluid"></p>
<p>Este gráfico de barras ilustra la distribución de la cantidad de productos por subcategoría dentro de la canasta básica que ha sido previamente filtrada. El <strong>eje horizontal (X)</strong> muestra las diversas subcategorías de productos, mientras que el <strong>eje vertical (Y)</strong>, denominado “Cantidades”, indica el número de productos disponibles por subcategoría, con una escala que va desde 0 hasta más de 100 unidades.</p>
<p>La característica más prominente del gráfico es la <strong>abrumadora concentración de productos en las primeras categorías</strong>. “Fruver” (aproximadamente 105 unidades) y “Cuidado Del Hogar” (alrededor de 100 unidades) presentan una cantidad excepcionalmente alta de opciones, lo que sugiere una gran variedad para los consumidores en estos segmentos. Les siguen “Harinas” (aproximadamente 65 unidades), “Carnes” (alrededor de 60 unidades) y “Quesos” (también alrededor de 60 unidades), que mantienen una oferta considerablemente robusta.</p>
<p>A partir de la subcategoría “Cuidado Personal” (aproximadamente 40 unidades), se observa una <strong>disminución drástica y una tendencia a la uniformidad</strong> en la cantidad de productos para el resto de las subcategorías. Un grupo extenso de subcategorías, que incluye “Aceites Comestibles”, “Alimentos Frescos”, “Bebidas Líquidas”, “Cuidado Del Cabello”, “Cuidado Dental”, “Golosinas Y Snacks”, “Granos”, “Leches Y Yogures”, “Licores” y “Panadería”, todas ellas muestran una cantidad muy similar y notablemente baja de productos, situándose <strong>justo por debajo de las 25 unidades</strong>. Esta homogeneidad en la baja cantidad sugiere una variedad limitada para el consumidor en un amplio espectro de productos esenciales.</p>
<ul>
<li><p>Existe una <strong>marcada polarización en la disponibilidad de productos</strong>, con una oferta muy abundante en las subcategorías de “Fruver” y “Cuidado Del Hogar”.</p></li>
<li><p>La <strong>mayoría de las categorías de la canasta básica filtrada presentan una cantidad de productos limitada y muy similar</strong> entre sí, lo que podría implicar opciones restringidas para el consumidor.</p></li>
<li><p>La distribución de la cantidad de productos es <strong>extremadamente asimétrica</strong>, con una caída abrupta después de las primeras categorías y una meseta de baja variedad en las restantes.</p></li>
</ul>
<hr>
</section>
<section id="gráfico-de-barras-de-las-categorías" class="level4" style="color: lightblue">
<h4 style="color: lightblue" class="anchored" data-anchor-id="gráfico-de-barras-de-las-categorías">Gráfico de barras de las categorías</h4>
<p><img src="images/clipboard-1464624892.png" class="img-fluid"></p>
<p>Este gráfico de barras ilustra la cantidad de productos disponibles para una amplia gama de categorías de todos los datos de DataPrecio. El <strong>eje horizontal (X)</strong> muestra las diversas categorías de productos, ordenadas de mayor a menor cantidad. El <strong>eje vertical (Y)</strong>, denominado “Cantidades”, indica el número de productos por categoría, con una escala que se extiende desde 0 hasta casi 500 unidades.</p>
<p>La característica más sobresaliente de este gráfico es la <strong>extremada disparidad en la cantidad de productos entre las categorías</strong>, revelando una distribución altamente sesgada. Las primeras categorías exhiben una abundancia excepcional: “Golosinas Y Snacks” (aproximadamente 490 unidades), “Bebidas Líquidas” (alrededor de 260 unidades), “Leches Y Yogures” (cerca de 180 unidades), “Cuidado Del Hogar” (aproximadamente 160 unidades) y “Misceláneos” (cerca de 125 unidades). Estas categorías dominan claramente la oferta en términos de variedad de productos.</p>
<p>A partir de “Cuidado Personal” (alrededor de 110 unidades), la cantidad de productos por categoría experimenta una <strong>disminución pronunciada y constante</strong>, formando una “cola larga” que se extiende a lo largo de la mayoría del gráfico. Categorías como “Cuidado Del Cabello”, “Repostería”, “Salsas”, “Granos” y “Carnes” muestran una cantidad que va decreciendo progresivamente desde aproximadamente 95 hasta 50 unidades.</p>
<p>Hacia el final del gráfico, la cantidad de productos por categoría se vuelve <strong>extremadamente baja</strong>, con muchas categorías registrando menos de 10 o incluso 5 unidades. Ejemplos incluyen “Cigarrillos Y Tabacos”, “Fungicidas”, “Pesticidas”, “Snacks Integrales”, entre otras. Esta marcada reducción indica una variedad muy limitada en estas áreas, lo que podría implicar escasez de opciones para los consumidores que buscan productos en dichos segmentos.</p>
<ul>
<li><p>Existe una <strong>altísima concentración de variedad de productos en muy pocas categorías iniciales</strong>, lideradas por “Golosinas Y Snacks” y “Bebidas Líquidas”.</p></li>
<li><p>La <strong>distribución de la cantidad de productos por categoría sigue un patrón de “cola larga”</strong>, con una rápida disminución de la variedad después de las primeras categorías.</p></li>
<li><p>Un <strong>amplio número de categorías presenta una oferta muy limitada</strong>, lo que restringe significativamente las opciones del consumidor en esos segmentos.</p></li>
</ul>
<hr>
</section>
</section>
</section>
<section id="análisis-de-la-evolución-de-los-precios-y-del-dashboard" class="level2" style="color: #F0DAA4">
<h2 style="color: #F0DAA4" class="anchored" data-anchor-id="análisis-de-la-evolución-de-los-precios-y-del-dashboard">Análisis de la Evolución de los Precios y del Dashboard</h2>
<section id="análisis-del-gráfico" class="level3" style="color: #F0DAA4">
<h3 style="color: #F0DAA4" class="anchored" data-anchor-id="análisis-del-gráfico"><strong>Análisis del Gráfico:</strong></h3>
<p>De manera consistente, <strong>Central Madeirense</strong> se posiciona como el supermercado que ofrece la canasta básica al costo más bajo durante todo el lapso de observación. Seguidamente, <strong>Supermercados Gama</strong> se ubica en un rango intermedio de precios. Finalmente, <strong>Plaza’s</strong> muestra, de forma sostenida, el costo más elevado para la canasta básica, manteniéndose consistentemente como la opción de mayor precio entre los tres. Es importante notar que, si bien la jerarquía general se mantiene robusta, en algunos puntos específicos del período analizado, las curvas de costo de Gama y Plaza’s se entrecruzan o aproxima muy estrechamente, indicando momentos de mayor paridad; no obstante, la tendencia predominante y el valor global de la canasta confirman que Plaza’s conserva su posición como la opción más costosa.</p>
</section>
<section id="análisis-de-data-table-basic-datatable" class="level3" style="color: #F0DAA4">
<h3 style="color: #F0DAA4" class="anchored" data-anchor-id="análisis-de-data-table-basic-datatable"><strong>Análisis de Data Table (Basic DataTable):</strong></h3>
<p>Continuando con el análisis, el dashboard presentado complementa de manera crucial la visualización gráfica al ofrecer una tabla interactiva, construida con el paquete <code>DT</code> con la ayuda del tutorial para uso del paquete <code>Shiny</code> en la elaboración de una “<strong>Basic DataTable”</strong>, que detalla la composición de la canasta básica seleccionada para esta investigación.&nbsp;</p>
<p>La tabla contiene un total de 159 datos, desglosados en aproximadamente 32 marcas, 22 categorías y 40 subcategorías, lo que evidencia la exhaustividad de la recopilación de datos. Para cada entrada, se presentan los precios tanto en dólares como en bolívares, con esta última cifra actualizada en función del tipo de cambio oficial más reciente <strong>(Oficial, no especulativo).</strong> Además, se incluyen detalles como la categoría, subcategoría, marca, la tienda específica donde se registró el precio, la fecha de descarga de dichos precios y un identificador único para el producto (<code>productID</code>).</p>
<p>Por ejemplo, si un usuario busca “Pollo” en la tabla, podrá observar rápidamente la categoría, subcategoría, ID del producto y sus precios correspondientes en bolívares y dólares en cada uno de los supermercados analizados. A través de esta búsqueda individual, se puede notar que, aunque Central Madeirense se posiciona consistentemente como el supermercado con la canasta básica de menor valor total, un producto específico como el “Pollo” tiene un menor valor en Gama y un mayor valor en Central Madeirense. Esta capacidad de búsqueda y comparación individual es vital para comprender las particularidades de los precios en cada establecimiento, permitiendo hacer una análisis desagregado más allá del costo total de la canasta.</p>
<hr>
</section>
</section>
<section id="bibliografía-consultada" class="level2" style="color: #F0DAA4">
<h2 style="color: #F0DAA4" class="anchored" data-anchor-id="bibliografía-consultada">Bibliografía Consultada</h2>
<p><a href="https://r4ds.had.co.nz/iteration.html?q=loop#for-loops">21 Iteration | R for Data Science</a></p>
<p><a href="https://intro2r.com/loops.html">7.5 Loops | An Introduction to R</a></p>
<p><a href="https://shiny.posit.co/r/gallery/widgets/basic-datatable/">Basic DataTable - Shiny</a></p>
<p><a href="https://ucveconomia-r4ds-2025-1.netlify.app/clases/clase_13#/title-slide">Ciencia de Datos para Economistas</a></p>
<p><a href="https://ucveconomia-r4ds-2025-1.netlify.app/clases/clase_19.html?#/title-slide">Clase 19: Selección, Agrupar y Crear Sumarios – UCV Economía R4DS</a></p>
<p><a href="https://rstudio.github.io/shinydashboard/get_started.html">Getting started with Shiny Dashboard - rstudio.github.io</a></p>
<p><a href="https://shiny.posit.co/r/articles/build/datatables/">How to use DataTables in a Shiny App - Shiny</a></p>
<p><a href="https://quarto-org.translate.goog/docs/output-formats/html-themes.html?_x_tr_sl=en&amp;_x_tr_tl=es&amp;_x_tr_hl=es&amp;_x_tr_pto=tc">HTML Theming – Quarto</a></p>
<p><a href="https://shiny.posit.co/r/gallery/government-public-sector/nz-trade-dash/">New Zealand Trade Intelligence Dashboard - Shiny</a></p>
<p><a href="https://rstudio.github.io/shinydashboard/structure.html#structure-overview">Shiny Dashboard Structure - rstudio.github.io</a></p>
<p><a href="https://ucveconomia-r4ds-2025-1.netlify.app/clases/clase_18.html?#/title-slide">UCV Economía R4DS – Clase 18: Selección, Agrupar y Crear Sumarios</a></p>
<p><a href="https://ucveconomia-r4ds-2025-1.netlify.app/clases/clase_23#/quarto-dashboards">UCV Economía R4DS – Clase 23: Quarto Dashboards</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>